version: '3.7'

services:
  httpd:
    build: .
    ports:
      - '80:80'
      - '443:443'
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./httpd.conf
        target: /etc/apache2/apache2.conf
      - type: volume
        source: letsencrypt
        target: /etc/letsencrypt
      - type: volume
        source: www-html
        target: /var/www/html

volumes:
  letsencrypt:
  www-certbot:
  www-html:

